### ISSUE TITLE
Failure to inject

### ISSUE THREAD

**Issue by jiaaluo** [khang06/mhynot2#2]
From cheat engine 7.4 I seem to be getting this error message
dllInject failed: Failed injecting the DLL
Force load module failed:failed finding address of KERNEL32!InitOnceExecuteOnce

**Comment by khang06** [comment]
you launched the game through x64dbg and injected it before the game initialized, right?

**Comment by jiaaluo** [comment]
yes, i try through launcher executable and that seems to "work" however no console application seems to be run

**Comment by khang06** [comment]
did you compile the dll with static minhook? minhook as a dynamic library doesn't seem to inject properly

**Comment by jiaaluo** [comment]
i did compile with static minhook

**Comment by khang06** [comment]
yeah, i probably should've clarified that i only had the debug build configuration set up properly
