### ISSUE TITLE
[Question] [Need help] Is it possible to run it in sandbox?

### ISSUE THREAD

**Issue by ameaninglessname** [khang06/mhynot2#3]
> I think requiring a kernel driver to play a (mostly) single-player game is worse.

I totally agree with that.

I don't want cheating, I just want to run it with [Sandbox](https://github.com/sandboxie-plus/Sandboxie),

Is it possible now?

**Comment by khang06** [comment]
i haven't tested, so i don't know. i do know that it at least allows the game to run without admin permission though

**Comment by khang06** [comment]
an alternative injector is provided in the readme and repo
